###################################
#服务启动端口的配置
###################################
server:
  port: ${server-port}

#注册中心
spring:
  application:
    name: sc-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    #################################
    #   gateway相关配置
    #################################
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
      #    路由定义
      routes:
        - id: api-manage
          uri: lb://sc-portal
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1

        - id: admin-manage
          uri: lb://sc-admin
          predicates:
            - Path=/login

        - id: cas-manage
          uri: lb://sc-cas
          predicates:
            - Path=/oauth/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8080/rsa/publicKey' #配置RSA的公钥访问地址
secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/auth/token"
      - "/api/user"